# SDAAS Certificate Verification — GitHub Actions workflow
#
# Add this to your repo at .github/workflows/verify-synthetic-data.yml
#
# Prerequisites:
#   1. Purchase a SDAAS.io certificate for your synthetic dataset
#   2. Add the certificate ID to GitHub Secrets: SDAAS_CERT_ID
#   3. (Optional) Add SDAAS_EXPECTED_KEY_ID to pin the signing key
#
# Usage:
#   This workflow runs on every push to main/staging.
#   It verifies the certificate BEFORE using the dataset in tests.

name: Verify Synthetic Dataset Certificate

on:
  push:
    branches: [main, staging]
  workflow_dispatch: # Allow manual runs

jobs:
  verify-cert:
    name: Verify SDAAS Certificate
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Option A: Self-contained verification (no npm install needed)
      - name: Download SDAAS verification script
        run: |
          curl -fsSL \
            https://raw.githubusercontent.com/Sdaas-io/sdaas-public/main/examples/ci-verify/verify.mjs \
            -o verify.mjs

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Verify certificate
        env:
          SDAAS_CERT_ID: ${{ secrets.SDAAS_CERT_ID }}
          SDAAS_EXPECTED_KEY_ID: ${{ secrets.SDAAS_EXPECTED_KEY_ID }}
        run: node verify.mjs

      # Option B: Use @sdaas/sdk (uncomment if you prefer the full SDK)
      # - name: Install SDK
      #   run: npm install @sdaas/sdk
      # - name: Verify via SDK
      #   run: |
      #     node --input-type=module <<'EOF'
      #     import { SdaasClient } from "@sdaas/sdk";
      #     const client = new SdaasClient();
      #     const { result } = await client.fetchAndVerify(process.env.SDAAS_CERT_ID);
      #     console.log(result);
      #     if (!result.verified) { console.error("Certificate verification failed"); process.exit(1); }
      #     EOF
      #   env:
      #     SDAAS_CERT_ID: ${{ secrets.SDAAS_CERT_ID }}

  use-dataset:
    name: Run tests with certified dataset
    runs-on: ubuntu-latest
    needs: verify-cert  # Only runs if certificate is verified

    steps:
      - uses: actions/checkout@v4

      - name: Download certified dataset
        env:
          SDAAS_CERT_ID: ${{ secrets.SDAAS_CERT_ID }}
        run: |
          # Replace with your actual dataset download URL
          curl -fsSL "https://your-storage.example.com/datasets/${SDAAS_CERT_ID}/dataset.csv" \
            -o dataset.csv

      - name: Run tests with certified dataset
        run: |
          # Replace with your actual test command
          echo "Running tests with certified synthetic dataset..."
          # npm test -- --dataset=dataset.csv
